# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: nationbuilder-ruby 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "nationbuilder-ruby"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Walmsley", "David Huie"]
  s.date = "2014-01-07"
  s.description = "A Ruby client for the NationBuilder API"
  s.email = ["dan@nationbuider.com", "david@nationbuilder.com"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-gemset",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/nationbuilder.rb",
    "lib/nationbuilder/client.rb",
    "lib/nationbuilder/controller.rb",
    "lib/nationbuilder/events_controller.rb",
    "lib/nationbuilder/model/address.rb",
    "lib/nationbuilder/model/autoresponse_details.rb",
    "lib/nationbuilder/model/base.rb",
    "lib/nationbuilder/model/event.rb",
    "lib/nationbuilder/model/event_shift.rb",
    "lib/nationbuilder/model/page_base.rb",
    "lib/nationbuilder/model/person.rb",
    "lib/nationbuilder/model/point_of_contact.rb",
    "lib/nationbuilder/model/rsvp_form_settings.rb",
    "lib/nationbuilder/model/site.rb",
    "lib/nationbuilder/model/venue.rb",
    "lib/nationbuilder/oauth_client.rb",
    "lib/nationbuilder/people_controller.rb",
    "lib/nationbuilder/sites_controller.rb",
    "nationbuilder-ruby.gemspec",
    "spec/client_spec.rb",
    "spec/oauth_client_spec.rb",
    "spec/people_controller_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/3dna/nationbuilder-ruby"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "A Ruby client for the NationBuilder API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, ["~> 4.0.2"])
      s.add_runtime_dependency(%q<oauth2>, ["~> 0.9.2"])
      s.add_runtime_dependency(%q<virtus>, ["~> 1.0.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14.1"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.8.2"])
      s.add_development_dependency(%q<vcr>, ["~> 2.8.0"])
    else
      s.add_dependency(%q<activemodel>, ["~> 4.0.2"])
      s.add_dependency(%q<oauth2>, ["~> 0.9.2"])
      s.add_dependency(%q<virtus>, ["~> 1.0.1"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.0"])
      s.add_dependency(%q<rdoc>, ["~> 4.1.0"])
      s.add_dependency(%q<rspec>, ["~> 2.14.1"])
      s.add_dependency(%q<simplecov>, ["~> 0.8.2"])
      s.add_dependency(%q<vcr>, ["~> 2.8.0"])
    end
  else
    s.add_dependency(%q<activemodel>, ["~> 4.0.2"])
    s.add_dependency(%q<oauth2>, ["~> 0.9.2"])
    s.add_dependency(%q<virtus>, ["~> 1.0.1"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.0"])
    s.add_dependency(%q<rdoc>, ["~> 4.1.0"])
    s.add_dependency(%q<rspec>, ["~> 2.14.1"])
    s.add_dependency(%q<simplecov>, ["~> 0.8.2"])
    s.add_dependency(%q<vcr>, ["~> 2.8.0"])
  end
end

